# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_phone', models.CharField(max_length=50)),
                ('Employee_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentor_email', models.CharField(max_length=50)),
                ('Mentor_name', models.CharField(max_length=50)),
                ('Mentor_phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=15)),
                ('Student_name', models.CharField(max_length=50)),
                ('Student_email', models.CharField(max_length=25)),
                ('Student_grade', models.CharField(default='F', max_length=2)),
                ('Parents_email', models.CharField(max_length=25)),
                ('Parents_phone', models.CharField(max_length=15)),
                ('School', models.CharField(max_length=50)),
                ('Emp_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='home.Employee')),
                ('Men_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='home.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Mname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Mentor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment2', to='home.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Student'),
        ),
    ]
