# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 22:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_phone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('Employee_email', models.EmailField(max_length=200)),
                ('Employee_Address', models.CharField(max_length=200)),
                ('Employee_Id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mentor_email', models.EmailField(default='X@gmail.com', max_length=49)),
                ('Mentor_name', models.CharField(max_length=49)),
                ('Mentor_phone', models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('Mentor_Address', models.CharField(max_length=200)),
                ('Mentor_Gender', models.CharField(default='X', help_text='Enter F or M', max_length=10)),
                ('Mentor_Id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=15)),
                ('Student_name', models.CharField(max_length=49)),
                ('Student_email', models.EmailField(default='X@gmail.com', max_length=25)),
                ('Student_grade', models.CharField(max_length=10)),
                ('Parents_email', models.EmailField(default='X@gmail.com', max_length=200)),
                ('Parents_phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')])),
                ('School', models.CharField(max_length=49)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empemail', to='home.Employee')),
                ('Men_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menemail', to='home.Mentor')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Mname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Mentor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment2', to='home.Student'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appointment', to='home.Student'),
        ),
    ]
