# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Employee_email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='Mentor_email',
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Address',
            field=models.CharField(default='Omaha', max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Id',
            field=models.CharField(default='999', max_length=10),
        ),
        migrations.AddField(
            model_name='mentor',
            name='Mentor_Address',
            field=models.CharField(default='Omaha', max_length=500),
        ),
        migrations.AddField(
            model_name='mentor',
            name='Mentor_Id',
            field=models.CharField(default='999', max_length=10),
        ),
        migrations.AddField(
            model_name='mentor',
            name='Mentor_Sex',
            field=models.CharField(default='null', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='Emp_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Employee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Men_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Mentor'),
        ),
    ]
