# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171020_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Emp_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empemail', to='home.Employee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Men_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Menemail', to='home.Mentor'),
        ),
    ]
