# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 02:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171024_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_email',
            field=models.EmailField(default='X@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='mentor',
            name='Mentor_email',
            field=models.EmailField(default='X@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_phone',
            field=models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')]),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_Gender',
            field=models.CharField(default='X', help_text='Enter F or M', max_length=1),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_phone',
            field=models.CharField(help_text='Phone Number should be 10 digits', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Parents_email',
            field=models.EmailField(default='X@gmail.com', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='Parents_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('[0-9]')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_email',
            field=models.EmailField(default='X@gmail.com', max_length=25),
        ),
    ]
