# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171024_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
