# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_Address',
            field=models.CharField(max_length=200),
        ),
    ]
