# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171025_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Address',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_email',
            field=models.EmailField(default='X@gmail.com', max_length=49),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_name',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_Address',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_email',
            field=models.EmailField(default='X@gmail.com', max_length=49),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_name',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.CharField(max_length=49),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_name',
            field=models.CharField(max_length=49),
        ),
    ]
