# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-25 21:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171025_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Employee_Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Employee_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_Gender',
            field=models.CharField(default='X', help_text='Enter F or M', max_length=10),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Mentor_phone',
            field=models.CharField(help_text='Phone Number should be 10 digits', max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.RegexValidator('[0-9]')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Parents_email',
            field=models.EmailField(default='X@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='Student_grade',
            field=models.CharField(max_length=10),
        ),
    ]
